### ISSUE TITLE
Possible memory leak with LibGetFrame minor ver 42 and beyond

### ISSUE THREAD

**Issue by burnep** [clicketz/buff-overlay#3]
### Description

Memory usage has been very high lately so I was trying to figure out what changed between versions and i found that if I used an older version of libgetframe the memory usage goes down significantly.

### Buff Overlay Version

v11.5.9

### World of Warcraft Flavor

Retail

### Sterile Testing

Yes

### Editing Lua Files

No

### Frames Used

Blizzard

### Reproduction Steps

1. Use AddonUsage
2. Use new clean version of BO
3. Measure high memory with AddonUsage
4. Use everything the same except a previous version of libgetframe
5. Measure low/non spike memory with AddonUsage

### Last Working Version

v11.4.3

**Comment by clicketz** [comment]
This looks to be a tradeoff that LibGetFrame is making by using a coroutine. Instead of finishing executing immediately with whatever data is has, it takes a few frames and stores info in a temporary cache until complete. This is probably the memory spikes you're seeing.

I'll look into it a bit more thoroughly, but my initial reaction is that you can safely ignore this unless the memory isn't being collected by the garbage collector and just keeps increasing infinitely.

It *should*, overall, actually be a (minor) performance gain despite some scary looking memory numbers.
